# Generated by Django 2.2.6 on 2019-10-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191014_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='description',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], max_length=300),
        ),
    ]
