# Generated by Django 2.2.6 on 2019-10-22 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191014_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='choices',
        ),
        migrations.DeleteModel(
            name='Choices',
        ),
    ]
